AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/EndOfLine:
  Enabled: false
  EnforcedStyle: lf
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/MethodLength:
  Max: 12
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']